### ISSUE TITLE
Make the file path in integration tests relative

### ISSUE THREAD

**Issue by SinaChavoshi** [tensorflow/cloud#75]
Currently integration tests assuming they are being ran from root, this is to make their path relative so that regardless of where they are being executed they can be run 

current format
```python
tfc.run(
    entry_point="tests/testdata/mnist_example_using_ctl.py", ...
```

suggested path look up 
```python
# Path to the source code in test environment
TEST_DATA_PATH = os.path.join(
  os.path.dirname(os.path.abspath(__file__)), '../testdata/')

...
tfc.run(
    entry_point=os.path.join(TEST_DATA_PATH, 'mnist_example_using_fit_no_reqs.py'), ...

```

**Comment by ucdmkt** [comment]
I later realized that, due to mocking, it doesn't matter if [`self.test_data_path`](https://github.com/tensorflow/cloud/blob/master/src/python/tensorflow_cloud/core/tests/unit/containerize_test.py#L34-L42) is real or not. 

For this reason, it should not point to a real testdata file, for the sake of clarity.
